version: "3.9"

services:
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3308:3306"
    volumes:
      - db-volume:/var/lib/mysql
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm start
    ports:
        - '8000:3000'
    volumes:
        - ./front:/RailsReact
    depends_on:
        - web
volumes:
  bundle_path:
  db-volume: